server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://sh-cdb-r1lpp9qe.sql.tencentcdb.com:63759/personal_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Rayce++_github
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 192.168.96.129
    port: 6379
    password: '0000'


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
